name: bixalcom
config:
  via: 'nginx:1.25'
  database: 'mariadb:10.6.18'
services:
  appserver:
    overrides:
      environment:
        # These are used by phpmailer_smtp as the credentials if you want to test it locally.
        # These are set in platform.sh as variables only on prod.
        EMAIL_USERNAME: ''
        EMAIL_PASSWORD: ''
        # Used to enable recaptcha.
        RECAPTCHA_SECRET_KEY: ''
        # Show the contact form in the footer.
        SHOW_CONTACT_FORM_IN_FOOTER: 1
  cache:
    type: 'redis:6'
  node:
    type: 'node:22'
    build:
      - ./orch/build_node.sh
    scanner: false
    # This starts storybook as the node user, it's root by default here.
    # If this dies (sometimes it runs out of memory), run lando restart.
    # To see the output of why it dies lando ssh -s node -c 'cat /tmp/story_book_start.log'.
    command: ./orch/start_storty_book_docker.js
    globals:
      gulp-cli: latest
tooling:
  watch:
    service: node
    cmd:
      - "cd web/themes/custom/bixal_uswds/ && gulp watch"
  gulp:
    service: node
    cmd:
      - "cd web/themes/custom/bixal_uswds/ && gulp"
  build_node:
    service: node
    cmd:
      - ./orch/build_node.sh
