<?php

/**
 * @file
 * Primary module hooks for Site Wrapper module.
 */

use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function site_wrapper_theme($existing, $type, $theme, $path): array {
  return [
    'site_wrapper_header' => [
      'variables' => ['cl' => NULL],
    ],
    'site_wrapper_footer' => [
      'variables' => ['cl' => NULL],
    ],
    'site_wrapper_contextual_links_wrapper' => [
      'variables' => ['cl' => NULL, 'content' => NULL],
    ],
  ];
}

/**
 * Prepares variables for header template.
 *
 * Default template: bixal-uswds-header.html.twig.
 *
 * @param array $variables
 *   This function has no $variables.
 */
function template_preprocess_site_wrapper_header(array &$variables): void {
  $variables['logo'] = [
    'image' => theme_get_setting('logo.url'),
    'href' => Url::fromRoute('<front>')->toString(),
  ];
  $menu_name = 'main';
  $variables['#cache']['contexts'][] = 'user.permissions';
  $variables['#cache']['tags'][] = "config:system.menu.$menu_name";
  // This requires contextual_preprocess() to be called, this is not called for
  // theme functions defined in themes, only modules. I don't know why.
  // 'cl' corresponds to the first variable of this theme function, this is
  // needed for the contextual links to render properly.
  $variables['main_nav_cl'] = _site_wrapper_get_menu_contextual_links($menu_name);
  /** @var \Drupal\Core\Menu\MenuLinkTreeElement $menu_link */
  foreach (_site_wrapper_get_top_level_menu_tree($menu_name) as $menu_link) {
    // Top level menu links are not removed that are not allowed, must kick
    // them out manually.
    if (NULL === $menu_link->access || !$menu_link->access->isAllowed()) {
      continue;
    }
    /** @var \Drupal\menu_link_content\Plugin\Menu\MenuLinkContent $menu_link_content */
    $menu_link_content = $menu_link->link;
    $variables['nav'][] = [
      'label' => $menu_link_content->getTitle(),
      'current' => $menu_link->inActiveTrail,
      'href' => $menu_link_content->getUrlObject()->toString(),
    ];
  }

  $menu_name = 'mainnavcta';
  $variables['#cache']['tags'][] = "config:system.menu.$menu_name";
  $variables['main_nav_cta_cl'] = _site_wrapper_get_menu_contextual_links($menu_name);
  $menu_links = _site_wrapper_get_top_level_menu_tree($menu_name);
  if (!empty($menu_links)) {
    /** @var \Drupal\Core\Menu\MenuLinkTreeElement $cta_menu_link */
    $cta_menu_link = current($menu_links);
    $variables['cta'] = [
      'label' => $cta_menu_link->link->getTitle(),
      'href' => $cta_menu_link->link->getUrlObject()->toString(),
    ];
  }
}

/**
 * Prepares variables for footer template.
 *
 * Default template: bixal-uswds-footer.html.twig.
 *
 * @param array $variables
 *   This function has no $variables.
 */
function template_preprocess_site_wrapper_footer(array &$variables): void {
  $menu_name = 'footer';
  $variables['#cache']['contexts'][] = 'user.permissions';
  $variables['#cache']['tags'][] = "config:system.menu.$menu_name";
  // This requires contextual_preprocess() to be called, this is not called for
  // theme functions defined in themes, only modules. I don't know why.
  // 'cl' corresponds to the first variable of this theme function, this is
  // needed for the contextual links to render properly.
  $variables['footer_nav_cl'] = _site_wrapper_get_menu_contextual_links($menu_name);
  /** @var \Drupal\Core\Menu\MenuLinkTreeElement $menu_link */
  foreach (_site_wrapper_get_top_level_menu_tree($menu_name) as $menu_link) {
    // Top level menu links are not removed that are not allowed, must kick
    // them out manually.
    if (NULL === $menu_link->access || !$menu_link->access->isAllowed()) {
      continue;
    }
    /** @var \Drupal\menu_link_content\Plugin\Menu\MenuLinkContent $menu_link_content */
    $menu_link_content = $menu_link->link;
    $variables['nav'][] = [
      'label' => $menu_link_content->getTitle(),
      'current' => $menu_link->inActiveTrail,
      'href' => $menu_link_content->getUrlObject()->toString(),
    ];
  }
  $menu_name = 'legal';
  $variables['#cache']['contexts'][] = 'user.permissions';
  $variables['#cache']['tags'][] = "config:system.menu.$menu_name";
  // This requires contextual_preprocess() to be called, this is not called for
  // theme functions defined in themes, only modules. I don't know why.
  // 'cl' corresponds to the first variable of this theme function, this is
  // needed for the contextual links to render properly.
  $variables['legal_nav_cl'] = _site_wrapper_get_menu_contextual_links($menu_name);
  /** @var \Drupal\Core\Menu\MenuLinkTreeElement $menu_link */
  foreach (_site_wrapper_get_top_level_menu_tree($menu_name) as $menu_link) {
    // Top level menu links are not removed that are not allowed, must kick
    // them out manually.
    if (NULL === $menu_link->access || !$menu_link->access->isAllowed()) {
      continue;
    }
    /** @var \Drupal\menu_link_content\Plugin\Menu\MenuLinkContent $menu_link_content */
    $menu_link_content = $menu_link->link;
    $variables['legal'][] = [
      'label' => $menu_link_content->getTitle(),
      'current' => $menu_link->inActiveTrail,
      'href' => $menu_link_content->getUrlObject()->toString(),
    ];
  }
  $variables['socialNav'] = [
    'variant' => NULL,
    'aria_label' => t('Social links'),
    'items' => [
      [
        "href" => "https://www.linkedIn.com/company/bixal",
        "label" => t("Bixal LinkedIn"),
        "icon_path" => _bixal_uswds_get_storybook_icon_file_url('linkedin.svg')->toString(),
      ],
      [
        "href" => "https://www.facebook.com/bixal",
        "label" => t("Bixal Facebook"),
        "icon_path" => _bixal_uswds_get_storybook_icon_file_url('facebook.svg')->toString(),
      ],
      [
        "href" => "https://www.twitter.com/bixal",
        "label" => t("Bixal Twitter"),
        "icon_path" => _bixal_uswds_get_storybook_icon_file_url('twitter.svg')->toString(),
      ],
    ],
  ];
}

/**
 * Get the top level menu item links in a menu.
 *
 * @param string $menu_name
 *   A menu ID.
 *
 * @return array
 *   The menu link tree.
 */
function _site_wrapper_get_top_level_menu_tree(string $menu_name): array {
  $parameters = new MenuTreeParameters();
  // Don't show disabled links.
  $parameters->onlyEnabledLinks();
  // Only allow top level menu links.
  $parameters->setMinDepth(1);
  $parameters->setMaxDepth(1);
  $menu_tree = \Drupal::menuTree()->load($menu_name, $parameters);
  // Sort links and check access.
  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkNodeAccess'],
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
  ];
  return \Drupal::menuTree()->transform($menu_tree, $manipulators);
}

/**
 * Return a renderable contextual links for a menu.
 *
 * @param string $menu_name
 *   A menu ID.
 *
 * @return array
 *   A renderable array.
 *
 * @throws Exception
 */
function _site_wrapper_get_menu_contextual_links(string $menu_name): array {
  if (str_contains($menu_name, '-')) {
    throw new \Exception('Menus with a hyphen in the name will not print out the contextual links, more research needed.');
  }
  return [
    '#theme' => 'site_wrapper_contextual_links_wrapper',
    '#cl' => [
      '#contextual_links' => [
        'menu' => [
          'route_parameters' => ['menu' => $menu_name],
        ],
      ],
    ],
  ];
}
