name: Frontend formatting & linting

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install node
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci --timing
      - name: Lint Styles
        run: npm run format:styles
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install node
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci --timing
      - name: Lint Styles
        run: npm run lint:styles
