name: "Publish Storybook"

on: push

jobs:
  publish-sb:
    name: "Publish storybook"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Summary
        run: echo -e "| Description | URL |\n| --- | --- |\n| Build | ${{steps.chromatic.outputs.buildUrl}} |\n| Storybook Preview | ${{steps.chromatic.outputs.storybookUrl}} |" >> $GITHUB_STEP_SUMMARY
