name: Run validation with RoboValidate

on:
    # Run on any branch so validate branch can always run.
    push:
    # Commit message validation requires a target branch which is only available in a PR.
    pull_request:

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    tools: composer:v2
                    # https://github.com/shivammathur/setup-php?tab=readme-ov-file#disable-coverage
                    coverage: none

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer

            -   name: Install Composer dependencies and initialize Robo
                run: |
                    composer install --ignore-platform-reqs --optimize-autoloader --no-progress --no-ansi
                    # If a Robo command exits with a failure and a RoboFile.php does not exist
                    # a warning about 'Robo is not initialized here. Please run `robo init` to create a new RoboFile.'
                    # will be created, which might make users think that is what the error was caused by.
                    if [ ! -f "RoboFile.php" ]; then
                        vendor/bin/robo init
                    fi

            -   name: Validate a change to any branch
                if: github.event_name == 'push'
                run: |
                    ROBO_VALIDATE_BRANCH_NAME=${{ github.head_ref }} vendor/bin/robo validate:all non_pr

            -   name: Validate pull requests
                if: github.event_name == 'pull_request'
                run: |
                    ROBO_VALIDATE_TARGET_BRANCH="${{ github.base_ref }}" ROBO_VALIDATE_CURRENT_BRANCH="${{ github.head_ref }}" vendor/bin/robo validate:all only_pr
